baseURL = 'https://www.vuonhoaly.com/'
title = 'Vườn Hoa Ly'
copyright = '2021 Vuonhoaly.com. All rights reserved.'
theme = 'hoaly'
defaultContentLanguage = 'zh-hans'
enableEmoji = true

[taxonomies]
category = 'categories'
tag = 'tags'

[languages]
[languages.zh-hans]
languageCode = 'zh-hans'
weight = 10

[markup]
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
lineAnchors = ''
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = true
style = 'github'
tabWidth = 2